"""added categories

Revision ID: 047b98a45156
Revises: 9b01a6429b69
Create Date: 2019-04-02 12:39:35.687772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047b98a45156'
down_revision = '9b01a6429b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('category', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'category')
    # ### end Alembic commands ###
