"""DA date

Revision ID: 9b01a6429b69
Revises: 2fd1322392f0
Create Date: 2019-02-06 14:28:15.221708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b01a6429b69'
down_revision = '2fd1322392f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dA_timestamp', sa.Date(), nullable=True))
    op.create_index(op.f('ix_user_dA_timestamp'), 'user', ['dA_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_dA_timestamp'), table_name='user')
    op.drop_column('user', 'dA_timestamp')
    # ### end Alembic commands ###
